"""initial schema: all PRD §7 tables, monthly requests partitions, append-only ledger

Revision ID: 0001
Revises:
Create Date: 2026-09-28 07:38:41.927911

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

CREATE_REQUESTS_PARTITION_FN = """
CREATE FUNCTION create_requests_partition(month date) RETURNS text
LANGUAGE plpgsql AS $$
DECLARE
    month_start date := date_trunc('month', month)::date;
    partition_name text := format('requests_%s', to_char(month_start, 'YYYY_MM'));
BEGIN
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS %I PARTITION OF requests FOR VALUES FROM (%L) TO (%L)',
        partition_name,
        month_start::timestamp AT TIME ZONE 'UTC',
        (month_start + interval '1 month')::timestamp AT TIME ZONE 'UTC'
    );
    RETURN partition_name;
END;
$$
"""

LEDGER_REJECT_MUTATION_FN = """
CREATE FUNCTION ledger_entries_reject_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'ledger_entries is append-only: % is not allowed', TG_OP
        USING HINT = 'Record a correction as a new ledger entry.';
END;
$$
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models",
        sa.Column("public_name", sa.Text(), nullable=False),
        sa.Column("upstream_id", sa.Text(), nullable=False),
        sa.Column("api_format", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("min_tier", sa.Text(), server_default="basic", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("context_window", sa.Integer(), nullable=True),
        sa.Column(
            "price_input_per_m",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "price_output_per_m",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "price_cache_write_per_m",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "price_cache_read_per_m",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "api_format IN ('openai', 'anthropic', 'both')", name=op.f("ck_models_api_format")
        ),
        sa.CheckConstraint(
            "category IN ('official', 'experimental')", name=op.f("ck_models_category")
        ),
        sa.CheckConstraint("min_tier IN ('basic', 'advanced')", name=op.f("ck_models_min_tier")),
        sa.CheckConstraint(
            "price_input_per_m >= 0 AND price_output_per_m >= 0"
            " AND price_cache_write_per_m >= 0 AND price_cache_read_per_m >= 0",
            name=op.f("ck_models_prices_non_negative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models")),
        sa.UniqueConstraint("public_name", name=op.f("uq_models_public_name")),
    )
    op.create_table(
        "projects",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("official_only", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("slug", name=op.f("uq_projects_slug")),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
        sa.UniqueConstraint("key", name=op.f("uq_settings_key")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), server_default="member", nullable=False),
        sa.Column("tier", sa.Text(), server_default="basic", nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("balance_idr", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "low_balance_threshold_idr",
            sa.BigInteger(),
            server_default=sa.text("10000"),
            nullable=False,
        ),
        sa.Column("daily_cap_idr", sa.BigInteger(), nullable=True),
        sa.Column(
            "leaderboard_opt_out", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('member', 'admin')", name=op.f("ck_users_role")),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'pending')", name=op.f("ck_users_status")
        ),
        sa.CheckConstraint("tier IN ('basic', 'advanced')", name=op.f("ck_users_tier")),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "api_keys",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("key_hash", sa.Text(), nullable=False),
        sa.Column("key_prefix", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("daily_cap_idr", sa.BigInteger(), nullable=True),
        sa.Column("model_allowlist", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active', 'revoked')", name=op.f("ck_api_keys_status")),
        sa.CheckConstraint(
            "char_length(key_hash) = 64", name=op.f("ck_api_keys_key_hash_sha256_hex")
        ),
        sa.CheckConstraint(
            "char_length(key_prefix) = 12", name=op.f("ck_api_keys_key_prefix_length")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_api_keys_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_api_keys_key_hash")),
    )
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("target_type", sa.Text(), nullable=False),
        sa.Column("target_id", sa.Text(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_hash", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_audit_logs_actor_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_table(
        "topup_requests",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("amount_requested_idr", sa.BigInteger(), nullable=False),
        sa.Column("amount_approved_idr", sa.BigInteger(), nullable=True),
        sa.Column("proof_path", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected')", name=op.f("ck_topup_requests_status")
        ),
        sa.CheckConstraint(
            "amount_requested_idr > 0", name=op.f("ck_topup_requests_amount_requested_positive")
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_topup_requests_reviewed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_topup_requests_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topup_requests")),
    )
    op.create_index(op.f("ix_topup_requests_status"), "topup_requests", ["status"], unique=False)
    op.create_index(
        op.f("ix_topup_requests_user_id_created_at"),
        "topup_requests",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "usage_daily",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("model_id", sa.Uuid(), nullable=False),
        sa.Column("project", sa.Text(), nullable=True),
        sa.Column("input_tokens", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "cache_write_tokens", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "cache_read_tokens", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("cost_idr", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("request_count", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_id"], ["models.id"], name=op.f("fk_usage_daily_model_id_models")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_usage_daily_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_daily")),
    )
    op.create_index(
        "uq_usage_daily_day_user_model_project",
        "usage_daily",
        ["day", "user_id", "model_id", "project"],
        unique=True,
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "ledger_entries",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("amount_idr", sa.BigInteger(), nullable=False),
        sa.Column("balance_after_idr", sa.BigInteger(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=True),
        sa.Column("topup_request_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(type NOT IN ('topup', 'refund') OR amount_idr > 0)"
            " AND (type <> 'usage' OR amount_idr <= 0)",
            name=op.f("ck_ledger_entries_amount_sign"),
        ),
        sa.CheckConstraint(
            "type <> 'adjustment' OR (note IS NOT NULL AND btrim(note) <> '')",
            name=op.f("ck_ledger_entries_adjustment_requires_note"),
        ),
        sa.CheckConstraint(
            "type IN ('topup', 'usage', 'adjustment', 'refund')",
            name=op.f("ck_ledger_entries_type"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_ledger_entries_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["topup_request_id"],
            ["topup_requests.id"],
            name=op.f("fk_ledger_entries_topup_request_id_topup_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ledger_entries_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_entries")),
    )
    op.create_index(
        op.f("ix_ledger_entries_request_id"), "ledger_entries", ["request_id"], unique=False
    )
    op.create_index(
        op.f("ix_ledger_entries_user_id_created_at"),
        "ledger_entries",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "requests",
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("api_key_id", sa.Uuid(), nullable=True),
        sa.Column("model_id", sa.Uuid(), nullable=True),
        sa.Column("model_public_name", sa.Text(), nullable=True),
        sa.Column("project", sa.Text(), nullable=True),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("is_stream", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("status_code", sa.SmallInteger(), nullable=False),
        sa.Column("error_type", sa.Text(), nullable=True),
        sa.Column("input_tokens", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "cache_write_tokens", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "cache_read_tokens", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("usage_estimated", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("price_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cost_idr", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("ttft_ms", sa.Integer(), nullable=True),
        sa.Column("client_ip_hash", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["api_key_id"], ["api_keys.id"], name=op.f("fk_requests_api_key_id_api_keys")
        ),
        sa.ForeignKeyConstraint(
            ["model_id"], ["models.id"], name=op.f("fk_requests_model_id_models")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_requests_user_id_users")),
        sa.PrimaryKeyConstraint("id", "started_at", name=op.f("pk_requests")),
        postgresql_partition_by="RANGE (started_at)",
    )
    op.create_index(
        op.f("ix_requests_model_id_started_at"),
        "requests",
        ["model_id", "started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_requests_project_started_at"), "requests", ["project", "started_at"], unique=False
    )
    op.create_index(
        op.f("ix_requests_user_id_started_at"), "requests", ["user_id", "started_at"], unique=False
    )
    op.create_index(
        "uq_requests_request_id_started_at", "requests", ["request_id", "started_at"], unique=True
    )
    # ### end Alembic commands ###

    # requests is range-partitioned by month (UTC boundaries). The migration creates the
    # current month plus three ahead; the default partition catches anything outside them.
    # TODO(worker): call create_requests_partition() monthly so new months never land in
    # requests_default (a partition cannot be created while default holds rows in its range).
    op.execute(CREATE_REQUESTS_PARTITION_FN)
    op.execute(
        "SELECT create_requests_partition("
        "(date_trunc('month', now() AT TIME ZONE 'UTC') + make_interval(months => m))::date)"
        " FROM generate_series(0, 3) AS m"
    )
    op.execute("CREATE TABLE requests_default PARTITION OF requests DEFAULT")

    # ledger_entries is append-only (PRD §4.3.6): reject UPDATE, DELETE, and TRUNCATE.
    op.execute(LEDGER_REJECT_MUTATION_FN)
    op.execute(
        "CREATE TRIGGER ledger_entries_append_only BEFORE UPDATE OR DELETE ON ledger_entries"
        " FOR EACH ROW EXECUTE FUNCTION ledger_entries_reject_mutation()"
    )
    op.execute(
        "CREATE TRIGGER ledger_entries_no_truncate BEFORE TRUNCATE ON ledger_entries"
        " FOR EACH STATEMENT EXECUTE FUNCTION ledger_entries_reject_mutation()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER ledger_entries_no_truncate ON ledger_entries")
    op.execute("DROP TRIGGER ledger_entries_append_only ON ledger_entries")
    op.execute("DROP FUNCTION ledger_entries_reject_mutation()")
    op.execute("DROP FUNCTION create_requests_partition(date)")
    # Dropping the partitioned requests table below also drops every partition.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_requests_request_id_started_at", table_name="requests")
    op.drop_index(op.f("ix_requests_user_id_started_at"), table_name="requests")
    op.drop_index(op.f("ix_requests_project_started_at"), table_name="requests")
    op.drop_index(op.f("ix_requests_model_id_started_at"), table_name="requests")
    op.drop_table("requests")
    op.drop_index(op.f("ix_ledger_entries_user_id_created_at"), table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_request_id"), table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_index(
        "uq_usage_daily_day_user_model_project",
        table_name="usage_daily",
        postgresql_nulls_not_distinct=True,
    )
    op.drop_table("usage_daily")
    op.drop_index(op.f("ix_topup_requests_user_id_created_at"), table_name="topup_requests")
    op.drop_index(op.f("ix_topup_requests_status"), table_name="topup_requests")
    op.drop_table("topup_requests")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_table("users")
    op.drop_table("settings")
    op.drop_table("projects")
    op.drop_table("models")
    # ### end Alembic commands ###
